name: Semgrep

on:
  workflow_dispatch: {}
  push:
    branches: [ "Devsecops_Demo" ]
  pull_request: {}

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep SAST
        run: |
          semgrep scan --severity ERROR --error --include=src/**
